name: appinio_code_challenge
description: This is a code challenge requested by Appinio

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  flutter_bloc: ^8.0.0
  json_annotation: ^4.4.0
  chopper: ^4.0.4
  build_runner: ^2.1.5
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.1.1
  chopper_generator: ^4.0.3


flutter:
  uses-material-design: true

  assets:
    - assets/